services:
 sql:
  image: mcr.microsoft.com/azure-sql-edge
  environment:
   ACCEPT_EULA: "1"
   MSSQL_SA_PASSWORD: "Password@1"
  ports:
    - "1433:1433"
  volumes:
    - sql_data:/var/opt/mssql
 redis:
   image: redis:latest
   ports:
      - "6379:6379"
   volumes:
      - redis_data:/data
volumes:
  sql_data:
  redis_data: